23-Sep-21 20:37:28 - 10280 - INFO - A manager by username:09162491542 is signed up
23-Sep-21 20:37:42 - 10280 - ERROR - No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 14, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09162491542/products.txt'
23-Sep-21 20:37:42 - 10280 - ERROR - error in showing inventory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\menu.py", line 128, in sign_in
    Market.inventory_alert(username)
  File "D:\bootcamp\untitled2\HW9\New folder\market.py", line 83, in inventory_alert
    for item in all_products_list:
TypeError: 'NoneType' object is not iterable
23-Sep-21 20:37:42 - 10280 - INFO - A manager by username:09162491542 signed in
23-Sep-21 20:38:19 - 10280 - INFO - A market manager by username:09162491542 added a product
23-Sep-21 20:38:51 - 10280 - INFO - A market manager by username:09162491542 added a product
23-Sep-21 20:39:48 - 10280 - ERROR - No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 14, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09162491542/invoices.txt'
INFO:root:A manager by username:09162491542 signed in
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 14, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09162491542/invoices.txt'
WARNING:root:Try to open a not existed file
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 14, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09162491542/costumers.txt'
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 14, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09162491542/costumers.txt'
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
WARNING:root:Try to sign in with unavailable  username:9162491542
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A market manager by username:09162491542 added a product
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09026905228 is signed up
WARNING:root:Try to sign in with unavailable  username:09066905228
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09026905228/products.txt'
ERROR:root:error in showing inventory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\menu.py", line 127, in sign_in
    Market.inventory_alert(username)
  File "D:\bootcamp\untitled2\HW9\New folder\market.py", line 141, in inventory_alert
    for item in all_products_list:
TypeError: 'NoneType' object is not iterable
INFO:root:A manager by username:09026905228 signed in
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09026905228/invoices.txt'
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09026905228/products.txt'
ERROR:root:error in showing inventory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\menu.py", line 127, in sign_in
    Market.inventory_alert(username)
  File "D:\bootcamp\untitled2\HW9\New folder\market.py", line 141, in inventory_alert
    for item in all_products_list:
TypeError: 'NoneType' object is not iterable
INFO:root:A manager by username:09026905228 signed in
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09026905228/products.txt'
ERROR:root:error in showing inventory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\menu.py", line 127, in sign_in
    Market.inventory_alert(username)
  File "D:\bootcamp\untitled2\HW9\New folder\market.py", line 145, in inventory_alert
    for item in all_products_list:
TypeError: 'NoneType' object is not iterable
INFO:root:A manager by username:09026905228 signed in
INFO:root:Try to read not exist file (products.txt)
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09026905228/products.txt'
INFO:root:Try to read not exist file (products.txt)
INFO:root:A manager by username:09026905228 signed in
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09026905228/invoices.txt'
INFO:root:Try to read not exist file (invoices.txt)
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09026905228/invoices.txt'
INFO:root:Try to read not exist file (costumers.txt)
INFO:root:Try to read not exist file (costumers.txt)
INFO:root:Try to read not exist file (products.txt)
INFO:root:Try to read not exist file (products.txt)
INFO:root:A manager by username:09162491542 signed in
INFO:root:Try to re-register by username:09162491542
INFO:root:Try to re-register by username:09162491542
INFO:root:Try to re-register by username:09162491542
INFO:root:A manager by username:09178821383 is signed up
INFO:root:Try to re-register by username:09178821383
INFO:root:A manager by username:09171506720 is signed up
INFO:root:Try to read not exist file (products.txt)
INFO:root:A manager by username:09178821383 signed in
INFO:root:Try to read not exist file (products.txt)
INFO:root:Try to read not exist file (products.txt)
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09178821383/invoices.txt'
INFO:root:Try to read not exist file (invoices.txt)
ERROR:root:No such file or directory
Traceback (most recent call last):
  File "D:\bootcamp\untitled2\HW9\New folder\Markets_File_Handler.py", line 15, in read_file
    with open(self.file_path, 'r') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'Markets/09178821383/invoices.txt'
INFO:root:Try to read not exist file (costumers.txt)
INFO:root:Try to read not exist file (costumers.txt)
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
WARNING:root:Try to sign in with unavailable  username:0164291542
INFO:root:A manager by username:09162491542 signed in
WARNING:root:Try to sign in with unavailable  username:3
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:Try to re-register by username:09162491542
INFO:root:A manager by username:09162491542 signed in
WARNING:root:A user by username:09162491542 entered incorrect password
WARNING:root:Try to sign in with unavailable  username:0916249152
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
WARNING:root:A user by username:09162491542 entered incorrect password
WARNING:root:A user by username:09162491542 entered incorrect password
WARNING:root:A user by username:09162491542 entered incorrect password
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
INFO:root:A manager by username:09162491542 signed in
